import React from 'react';
import { TrendingUp } from 'lucide-react';
import { ServiceGigPage, ServiceGigPageProps } from '@/components/templates/ServiceGigPage';

const data: ServiceGigPageProps = {
  serviceName: 'Ads Management',
  tagline: 'I will run ROI-obsessed paid ad campaigns that scale your revenue — not just your spend',
  icon: <TrendingUp className="w-6 h-6 text-red-500" />,
  tags: ['Meta Ads', 'TikTok Ads', 'Google Ads', 'LinkedIn Ads', 'Media Buying'],
  heroImage: 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=1200&h=675&fit=crop',
  galleryImages: [
    'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=675&fit=crop',
    'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=1200&h=675&fit=crop',
    'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&h=675&fit=crop',
  ],
  about:
    'We do not run ads — we engineer revenue machines. Our paid media team manages seven-figure ad budgets across Meta, TikTok, Google, and LinkedIn, consistently delivering 3x–10x ROAS for e-commerce, lead-gen, and SaaS businesses. Every campaign is built on a foundation of audience research, creative testing, and relentless optimisation. We own the numbers, communicate clearly, and scale what works.',
  packages: [
    {
      name: 'Basic',
      label: 'Starter',
      price: 249,
      originalPrice: 299,
      delivery: 'Monthly',
      revisions: '2',
      description: 'Single-platform management — ideal for brands starting with one ad channel.',
      features: [
        '1 ad platform (Meta OR Google OR TikTok)',
        'Up to $3,000 monthly ad spend',
        'Campaign setup & audience research',
        'Monthly creative refresh (2 ads)',
        'Weekly performance report',
      ],
    },
    {
      name: 'Standard',
      label: 'Growth',
      price: 499,
      originalPrice: 599,
      delivery: 'Monthly',
      revisions: '5',
      description: 'Multi-platform campaigns for brands ready to dominate across channels.',
      features: [
        '3 ad platforms',
        'Up to $10,000 monthly ad spend',
        'Full funnel strategy (TOF → BOF)',
        'A/B creative testing (6 ads/month)',
        'Conversion tracking setup',
        'Bi-weekly strategy calls',
        'Competitor ad intelligence reports',
      ],
    },
    {
      name: 'Premium',
      label: 'Scale',
      price: 999,
      originalPrice: 1199,
      delivery: 'Monthly',
      revisions: 'Unlimited',
      description: 'Full-stack paid media management across all platforms with dedicated strategist.',
      features: [
        'All platforms — unlimited ad spend',
        'Dedicated media buyer + creative team',
        'Daily optimisation & bid management',
        'Unlimited ad creatives per month',
        'Landing page CRO recommendations',
        'Weekly 1:1 strategy calls',
        'Full attribution dashboard',
      ],
    },
  ],
  subServices: [
    {
      id: 'meta-ads',
      name: 'Meta Ads (Facebook & Instagram)',
      description: 'Full-funnel Meta campaigns from awareness to conversion — retargeting, lookalikes, and creative that stops the scroll.',
      detailDescription: 'Meta is still the most powerful paid acquisition channel when managed correctly. We build full-funnel campaigns — from cold audience awareness all the way to retargeting your warmest prospects — with scroll-stopping creative and copy that converts. Every week we test, analyse, and scale what\'s working while cutting what isn\'t.',
      image: 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=500&fit=crop',
      ],
      badge: 'Bestseller',
      deliveryDays: 30,
      startingPrice: 249,
      subOptionKey: 'Meta Ads',
      features: ['Audience research & segmentation', 'Retargeting & lookalike audiences', 'Creative testing framework'],
    },
    {
      id: 'tiktok-ads',
      name: 'TikTok Ads',
      description: 'Viral-first TikTok campaigns with native-style creatives that convert before viewers even realise it\'s an ad.',
      detailDescription: 'TikTok rewards brands that understand the platform — not those that repurpose tired ad formats from other channels. We create native-style creatives that blend into the feed and convert before viewers even realise it\'s an ad. Spark Ads, In-Feed placements, and creator collaborations managed as one joined-up strategy.',
      image: 'https://images.unsplash.com/photo-1611162617263-4ec3d744e0a3?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1611162617263-4ec3d744e0a3?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=800&h=500&fit=crop',
      ],
      badge: 'Hot',
      deliveryDays: 30,
      startingPrice: 249,
      subOptionKey: 'TikTok Ads',
      features: ['Spark Ads & In-Feed Ads', 'UGC-style creatives', 'TikTok Pixel setup'],
    },
    {
      id: 'google-ads',
      name: 'Google Ads (Search & Shopping)',
      description: 'Capture high-intent buyers with precision Search and Shopping campaigns that maximise ROAS and minimise wasted spend.',
      detailDescription: 'Google puts your brand directly in front of people who are already searching to buy. We build precision Search and Shopping campaigns with tight keyword structures, thorough negative lists, and Smart Bidding strategies that eliminate wasted spend and consistently grow your ROAS month over month.',
      image: 'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1553895501-af9e282e7fc1?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1522542550221-31fd19575a2d?w=800&h=500&fit=crop',
      ],
      badge: 'Most Popular',
      deliveryDays: 30,
      startingPrice: 299,
      subOptionKey: 'Google Ads',
      features: ['Keyword research & negative lists', 'Shopping feed optimisation', 'Conversion tracking & Smart Bidding'],
    },
    {
      id: 'linkedin-ads',
      name: 'LinkedIn Ads',
      description: 'B2B lead generation at scale with Sponsored Content, Lead Gen Forms, and precise job-title targeting.',
      detailDescription: 'LinkedIn is the only platform where you can target by job title, company size, seniority, and industry simultaneously — making it the most powerful B2B acquisition channel available. We run Sponsored Content, Lead Gen Forms, and InMail campaigns that put your offer directly in front of the exact decision-makers you need.',
      image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1553484771-371a605b060b?w=800&h=500&fit=crop',
      ],
      deliveryDays: 30,
      startingPrice: 349,
      subOptionKey: 'LinkedIn Ads',
      features: ['Job title & company targeting', 'Lead Gen Form campaigns', 'InMail & Sponsored Content'],
    },
    {
      id: 'media-buying',
      name: 'Media Buying & Planning',
      description: 'Strategic cross-channel media buying that allocates budget where it generates the highest ROI.',
      detailDescription: 'Knowing where to put your budget is half the battle. We analyse your full funnel, model attribution across every active channel, and allocate spend precisely where it generates the highest return. One unified monthly media plan that keeps your team aligned and every pound of ad spend accountable.',
      image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1543286386-713bdd548da4?w=800&h=500&fit=crop',
      ],
      deliveryDays: 30,
      startingPrice: 499,
      subOptionKey: 'Media Buying',
      features: ['Cross-channel budget allocation', 'Attribution modelling', 'Monthly media plan & reporting'],
    },
  ],
  faqs: [
    { q: 'Is ad spend included in your fee?', a: 'No — our fee covers management, strategy, and creative. Ad spend goes directly to the platforms through your own ad accounts.' },
    { q: 'How long before I see results?', a: 'Most campaigns see meaningful data within 7–14 days. Typical ROAS stabilises by week 3. We always set honest, data-backed expectations upfront.' },
    { q: 'Do you create ad creatives?', a: 'Yes. Standard and Premium packages include ad creative production. Basic includes 2 creatives per month; Premium is unlimited.' },
    { q: 'Can I pause or cancel at any time?', a: 'Yes. We work month-to-month with 14 days notice to wind down. No lock-in contracts.' },
    { q: 'What reporting do you provide?', a: 'Weekly snapshot reports plus a live dashboard you can access 24/7 showing spend, ROAS, CPL, and all KPIs in real time.' },
  ],
  reviewCount: 198,
  totalOrders: '380+',
};

export const AdsManagementPage: React.FC = () => <ServiceGigPage {...data} serviceSlug="ads-management" />;
