import React from 'react';
import { Smartphone } from 'lucide-react';
import { ServiceGigPage, ServiceGigPageProps } from '@/components/templates/ServiceGigPage';

const data: ServiceGigPageProps = {
  serviceName: 'App Development',
  tagline: 'I will design and build a stunning, high-performance mobile app that users cannot put down',
  icon: <Smartphone className="w-6 h-6 text-red-500" />,
  tags: ['Flutter', 'iOS App', 'Android App', 'Cross-Platform', 'UI/UX for Mobile'],
  heroImage: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=1200&h=675&fit=crop',
  galleryImages: [
    'https://images.unsplash.com/photo-1526367790999-0150786686a2?w=1200&h=675&fit=crop',
    'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=1200&h=675&fit=crop',
    'https://images.unsplash.com/photo-1555774698-0b77e0d5fac6?w=1200&h=675&fit=crop',
  ],
  about:
    'From concept to App Store — we build mobile applications that people actually use and love. Our team covers the full stack: beautiful UI/UX design, cross-platform Flutter development, native iOS (Swift) and Android (Kotlin), backend APIs, and deployment. We have launched 80+ apps across e-commerce, fitness, food delivery, fintech, and SaaS — many achieving top-10 rankings in their categories within 90 days.',
  packages: [
    {
      name: 'Basic',
      label: 'MVP',
      price: 699,
      originalPrice: 999,
      delivery: '21 Days',
      revisions: '2',
      description: 'A lean, launch-ready MVP to validate your app idea with real users fast.',
      features: [
        'Up to 5 screens / core feature set',
        'Flutter or React Native',
        'Firebase backend',
        'Push notification setup',
        'App Store / Play Store submission',
        '2-week post-launch support',
      ],
    },
    {
      name: 'Standard',
      label: 'Full App',
      price: 1749,
      originalPrice: 2499,
      delivery: '45 Days',
      revisions: '5',
      description: 'Feature-complete app with custom UI, backend, and platform submission.',
      features: [
        'Unlimited screens',
        'Custom UI/UX design',
        'REST API + database backend',
        'Social login & payments',
        'Analytics integration',
        'App Store + Play Store submission',
        '1-month post-launch support',
      ],
    },
    {
      name: 'Premium',
      label: 'Enterprise',
      price: 3499,
      originalPrice: 4999,
      delivery: '60 Days',
      revisions: 'Unlimited',
      description: 'Enterprise-grade app with native builds, admin dashboard, and full DevOps pipeline.',
      features: [
        'Native iOS (Swift) + Android (Kotlin)',
        'Custom design system',
        'Node.js / Django backend',
        'Admin web dashboard',
        'Role-based access control',
        'CI/CD pipeline',
        'Performance & security audit',
        '3-month dedicated support',
      ],
    },
  ],
  subServices: [
    {
      id: 'flutter',
      name: 'Flutter Cross-Platform App',
      description: 'One codebase, two stores — Flutter apps that look and feel native on iOS and Android with blazing performance.',
      detailDescription: 'Flutter gives you a native-quality app for both iOS and Android from a single codebase — cutting development time and cost without sacrificing performance or polish. We handle design, development, backend integration, and App Store submission. Most Flutter MVPs go from brief to live in under 3 weeks.',
      image: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1555774698-0b77e0d5fac6?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1526367790999-0150786686a2?w=800&h=500&fit=crop',
      ],
      badge: 'Most Popular',
      deliveryDays: 21,
      startingPrice: 699,
      subOptionKey: 'Flutter',
      features: ['iOS & Android from one codebase', 'Firebase / Supabase backend', 'App Store + Play Store submission'],
    },
    {
      id: 'ios',
      name: 'Native iOS App (Swift)',
      description: 'Premium iOS experiences with SwiftUI, Apple ecosystem integrations, and pixel-perfect design that feels at home on iPhone.',
      detailDescription: 'If your audience is primarily on iPhone, there\'s no substitute for native SwiftUI development. We build pixel-perfect iOS apps with deep Apple ecosystem integrations — Health, Pay, Watch, Shortcuts — and a user experience that feels completely at home on iOS. Submitted and managed through your App Store account.',
      image: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=800&h=500&fit=crop',
      ],
      badge: 'Bestseller',
      deliveryDays: 30,
      startingPrice: 999,
      subOptionKey: 'iOS App',
      features: ['SwiftUI / UIKit', 'Apple Health, Pay, Watch integration', 'App Store submission & review'],
    },
    {
      id: 'android',
      name: 'Native Android App (Kotlin)',
      description: 'High-performance Android apps built with Kotlin and Jetpack Compose — optimised for the full Android device landscape.',
      detailDescription: 'Kotlin and Jetpack Compose give Android development a modern, expressive foundation. We build high-performance apps tested across the full Android device landscape — from budget phones to foldables — with Google Maps, Pay, and Firebase integrations built in from the ground up.',
      image: 'https://images.unsplash.com/photo-1526367790999-0150786686a2?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1526367790999-0150786686a2?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1607252650355-f7fd0460ccdb?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1622542796254-5b9c46ab0d2f?w=800&h=500&fit=crop',
      ],
      deliveryDays: 28,
      startingPrice: 899,
      subOptionKey: 'Android App',
      features: ['Kotlin + Jetpack Compose', 'Google Maps / Pay integration', 'Play Store submission'],
    },
    {
      id: 'cross-platform',
      name: 'Cross-Platform App (React Native)',
      description: 'React Native apps with near-native performance and full access to device APIs — great for teams with existing React knowledge.',
      detailDescription: 'If your team already works in React, React Native is the natural choice for mobile. Share business logic between your web and mobile products, access all native device APIs, and push OTA updates without an App Store re-submission for minor releases. Full iOS and Android coverage from a single codebase.',
      image: 'https://images.unsplash.com/photo-1555774698-0b77e0d5fac6?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1555774698-0b77e0d5fac6?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=500&fit=crop',
      ],
      deliveryDays: 25,
      startingPrice: 749,
      subOptionKey: 'Cross-Platform App',
      features: ['React Native + Expo', 'Shared codebase (iOS + Android)', 'OTA updates via EAS'],
    },
    {
      id: 'uiux-mobile',
      name: 'Mobile UI/UX Design',
      description: 'Research-backed, Figma-designed mobile interfaces that are intuitive, beautiful, and tested before a line of code is written.',
      detailDescription: 'Beautiful apps start with a great design process, not just great visuals. We conduct user research, map user flows, create wireframes, and produce high-fidelity Figma prototypes that are usability-tested before a single line of code is written. You see exactly what you\'re getting — and your users love it from day one.',
      image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1573867639040-6dd25fa5f597?w=800&h=500&fit=crop',
      ],
      badge: 'Hot',
      deliveryDays: 10,
      startingPrice: 349,
      subOptionKey: 'UI/UX for Mobile',
      features: ['User research & persona mapping', 'Wireframes → hi-fi Figma prototype', 'Usability testing & iteration'],
    },
  ],
  faqs: [
    { q: 'Which platform should I choose — Flutter or native?', a: 'Flutter is our default recommendation for most projects: faster delivery, lower cost, and 90% of native performance. Choose native when you need deep OS integrations (e.g. AR, system-level access).' },
    { q: 'Do you handle App Store / Play Store submission?', a: 'Yes. We prepare all assets, metadata, and screenshots, submit on your behalf, and manage any review feedback until approved.' },
    { q: 'Can you build the backend API as well?', a: 'Absolutely. Standard and Premium packages include a full backend. We use Node.js + MongoDB, Firebase, or Supabase depending on your requirements.' },
    { q: 'How do app updates work after launch?', a: 'We offer monthly maintenance retainers for ongoing updates. Flutter and React Native apps also support OTA (over-the-air) updates without App Store re-submission for minor changes.' },
    { q: 'What if I already have a design?', a: 'Great — we can build directly from your Figma files. We will review and flag any implementation issues before we start.' },
  ],
  reviewCount: 167,
  totalOrders: '300+',
};

export const AppDevelopmentPage: React.FC = () => <ServiceGigPage {...data} serviceSlug="app-development" />;
