import React from 'react';
import { Palette } from 'lucide-react';
import { ServiceGigPage, ServiceGigPageProps } from '@/components/templates/ServiceGigPage';

const data: ServiceGigPageProps = {
  serviceName: 'Graphic Design',
  tagline: 'I will craft premium brand visuals that make your audience feel something — and buy',
  icon: <Palette className="w-6 h-6 text-red-500" />,
  tags: ['Branding', 'Content Strategy', 'Social Media Content'],
  heroImage: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=1200&h=675&fit=crop',
  galleryImages: [
    'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=1200&h=675&fit=crop',
    'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=1200&h=675&fit=crop',
    'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=1200&h=675&fit=crop',
  ],
  about:
    'Your brand is the first impression — and first impressions convert. We design identity systems, content libraries, and social media assets that are not just beautiful but strategically engineered to trigger trust, recognition, and action. From full brand identity builds to scroll-stopping ad creatives, every pixel we produce has a purpose. Our designers have worked across fashion, tech, hospitality, and e-commerce verticals.',
  packages: [
    {
      name: 'Basic',
      label: 'Starter',
      price: 149,
      originalPrice: 199,
      delivery: '5 Days',
      revisions: '2',
      description: 'Core brand foundation — logo design and color palette to establish your visual identity.',
      features: [
        'Logo design (3 concepts)',
        'Color palette (primary + secondary)',
        'Typography pairing',
        'PNG, SVG, PDF deliverables',
        'Brand style mini-guide',
      ],
    },
    {
      name: 'Standard',
      label: 'Brand Kit',
      price: 319,
      originalPrice: 449,
      delivery: '10 Days',
      revisions: '5',
      description: 'Full brand kit — everything you need to look consistent and professional across all channels.',
      features: [
        'Everything in Basic',
        'Business card design',
        'Social media profile assets',
        'Email signature design',
        'Presentation slide template',
        'Brand guidelines PDF (15+ pages)',
      ],
    },
    {
      name: 'Premium',
      label: 'Full Identity',
      price: 699,
      originalPrice: 999,
      delivery: '14 Days',
      revisions: 'Unlimited',
      description: 'Complete visual identity system covering every touchpoint of your brand.',
      features: [
        'Everything in Standard',
        'Content strategy document',
        '20 social media post templates',
        'Ad creative pack (10 formats)',
        'Product mockup photography',
        'Motion graphics intro (5 sec)',
        'Packaging / label design',
      ],
    },
  ],
  subServices: [
    {
      id: 'branding',
      name: 'Brand Identity Design',
      description: 'Logo, color system, typography, and brand guidelines that define who you are and why people trust you.',
      detailDescription: 'Your brand is the first thing potential clients judge — and we make sure that judgement works in your favour. We design logos, colour systems, and typography pairings that communicate authority and trust at a glance. Every deliverable arrives in all formats you\'ll ever need, from print-ready PDF to scalable SVG.',
      image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1600494603989-9650cf6ddd3d?w=800&h=500&fit=crop',
      ],
      badge: 'Bestseller',
      deliveryDays: 5,
      startingPrice: 149,
      subOptionKey: 'Branding',
      features: ['Logo (3 concepts)', 'Color palette & typography', 'Brand guidelines PDF'],
    },
    {
      id: 'content-strategy',
      name: 'Content Strategy & Visual Planning',
      description: 'A data-driven content strategy paired with stunning visual templates to keep your brand consistent every week.',
      detailDescription: 'Posting without a plan is burning budget. We develop data-driven content strategies tied directly to your business goals, paired with professional visual templates that keep your brand consistent week after week. You\'ll always know what to post, when to post it, and exactly why it will work.',
      image: 'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=800&h=500&fit=crop',
      ],
      badge: 'Most Popular',
      deliveryDays: 7,
      startingPrice: 199,
      subOptionKey: 'Content Strategy',
      features: ['30-day content calendar', 'Platform-specific templates', 'Caption & hashtag strategy'],
    },
    {
      id: 'social-media-content',
      name: 'Social Media Content Pack',
      description: 'Scroll-stopping posts, stories, carousels, and ad creatives designed to drive engagement and sales.',
      detailDescription: 'Your content has 0.3 seconds to earn a scroll-stop. We design posts, stories, and carousels that convert browsers into followers and followers into buyers — not just pretty graphics, but content built around psychology and platform behaviour. Every asset is properly sized and formatted for maximum reach on each platform.',
      image: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1611162617263-4ec3d744e0a3?w=800&h=500&fit=crop',
      ],
      badge: 'Hot',
      deliveryDays: 5,
      startingPrice: 129,
      subOptionKey: 'Social Media Content',
      features: ['10 post designs', 'Story & reel templates', 'Ad creative formats (FB/IG/TikTok)'],
    },
  ],
  faqs: [
    { q: 'What file formats will I receive?', a: 'All deliverables come in print-ready PDF, web-optimised PNG, layered PSD/AI files, and scalable SVG — everything you need for both digital and print use.' },
    { q: 'Do I own the designs after purchase?', a: 'Yes, 100%. Once the project is complete and paid in full, you own all intellectual property and source files.' },
    { q: 'How do revisions work?', a: 'After each delivery round you give feedback, and we apply changes. Revisions are tracked on our shared design board for full transparency.' },
    { q: 'Can you match an existing brand style?', a: 'Absolutely. Just share your brand assets and style references and we will extend your existing identity seamlessly.' },
    { q: 'How long does a full brand identity take?', a: 'Typically 10–14 days from brief to final delivery for a Standard package. Premium projects can take 3 weeks depending on scope.' },
  ],
  reviewCount: 276,
  totalOrders: '450+',
};

export const GraphicDesignPage: React.FC = () => <ServiceGigPage {...data} serviceSlug="graphic-design" />;
