import React from 'react';
import { Search } from 'lucide-react';
import { ServiceGigPage, ServiceGigPageProps } from '@/components/templates/ServiceGigPage';

const data: ServiceGigPageProps = {
  serviceName: 'SEO / AEO',
  tagline: 'I will dominate Google — and every AI answer engine — so your brand gets found first, every time',
  icon: <Search className="w-6 h-6 text-red-500" />,
  tags: ['On-Page SEO', 'Technical SEO', 'Local SEO', 'AI Engine Optimization', 'Keyword Research', 'Link Building'],
  heroImage: 'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=1200&h=675&fit=crop',
  galleryImages: [
    'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=675&fit=crop',
    'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=1200&h=675&fit=crop',
    'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&h=675&fit=crop',
  ],
  about:
    'Google alone processes 8.5 billion searches daily — and the brands that rank at the top capture 90% of the clicks. We build SEO strategies that move the needle: technical foundations that satisfy Core Web Vitals, content architectures that own entire topic clusters, and backlink profiles that signal authority. We also specialise in AEO — Answer Engine Optimisation — ensuring your brand is cited by ChatGPT, Perplexity, and Google SGE. Results are typically visible within 60–90 days.',
  packages: [
    {
      name: 'Basic',
      label: 'Starter',
      price: 249,
      originalPrice: 299,
      delivery: 'Monthly',
      revisions: '2',
      description: 'Foundation SEO to fix technical issues and target your core keywords.',
      features: [
        'Technical SEO audit & fixes',
        'On-page optimisation (10 pages)',
        'Keyword research (30 terms)',
        'Google Search Console setup',
        'Monthly ranking report',
      ],
    },
    {
      name: 'Standard',
      label: 'Growth',
      price: 499,
      originalPrice: 599,
      delivery: 'Monthly',
      revisions: '5',
      description: 'Full SEO campaign — content, links, and technical — to capture significant organic traffic.',
      features: [
        'Everything in Starter',
        '4 SEO blog articles per month',
        'Link building (5 DR40+ backlinks)',
        'Local SEO (up to 3 locations)',
        'Schema markup implementation',
        'Core Web Vitals optimisation',
        'Competitor gap analysis',
      ],
    },
    {
      name: 'Premium',
      label: 'Authority',
      price: 799,
      originalPrice: 999,
      delivery: 'Monthly',
      revisions: 'Unlimited',
      description: 'Dominate both traditional search and AI answer engines with our full Authority programme.',
      features: [
        'Everything in Growth',
        'AI Engine Optimisation (AEO)',
        '8 expert-level content pieces/month',
        '15 DR50+ backlinks per month',
        'Featured snippet targeting',
        'E-E-A-T authority building',
        'Weekly strategy calls',
      ],
    },
  ],
  subServices: [
    {
      id: 'on-page-seo',
      name: 'On-Page SEO Optimisation',
      description: 'Title tags, meta descriptions, heading structure, internal linking, and content optimisation engineered to rank for your target keywords.',
      detailDescription: 'On-page SEO is the foundation every ranking is built on. We optimise your title tags, meta descriptions, heading structure, content depth, and internal linking for your exact target keywords. Every page we touch has a clear job: rank for the right term and convert the traffic it earns.',
      image: 'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1522542550221-31fd19575a2d?w=800&h=500&fit=crop',
      ],
      badge: 'Bestseller',
      deliveryDays: 7,
      startingPrice: 149,
      subOptionKey: 'On-Page SEO',
      features: ['Title & meta tag optimisation', 'Content depth & keyword placement', 'Internal linking strategy'],
    },
    {
      id: 'technical-seo',
      name: 'Technical SEO Audit & Fixes',
      description: 'Full crawl audit covering Core Web Vitals, site architecture, indexability, schema, and speed — then we fix everything we find.',
      detailDescription: 'If Google can\'t crawl and index your site correctly, no amount of content or backlinks will move the needle. We run a full technical audit — Core Web Vitals, site architecture, crawl budget, schema, canonicalisation — and then we fix every issue we find. No report-and-walk-away; we deliver a clean, properly indexable website.',
      image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&h=500&fit=crop',
      ],
      badge: 'Most Popular',
      deliveryDays: 14,
      startingPrice: 299,
      subOptionKey: 'Technical SEO',
      features: ['Core Web Vitals fixes', 'Crawl budget analysis', 'Schema markup implementation'],
    },
    {
      id: 'local-seo',
      name: 'Local SEO',
      description: 'Rank in Google\'s local pack and Maps for high-intent nearby searches — driving calls, visits, and leads from your area.',
      detailDescription: 'For businesses serving a local area, ranking in Google\'s local pack is the single highest-ROI SEO activity available. We optimise your Google Business Profile, build authoritative local citations, and generate a steady flow of verified reviews to push you to the top of the map pack and keep you there.',
      image: 'https://images.unsplash.com/photo-1526367790999-0150786686a2?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1526367790999-0150786686a2?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1577415124269-fc1140a69e91?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?w=800&h=500&fit=crop',
      ],
      deliveryDays: 30,
      startingPrice: 199,
      subOptionKey: 'Local SEO',
      features: ['Google Business Profile optimisation', 'Local citation building', 'Review generation system'],
    },
    {
      id: 'aeo',
      name: 'AI Engine Optimisation (AEO)',
      description: 'Make your brand the source ChatGPT, Perplexity, and Google SGE cite when users ask questions in your niche.',
      detailDescription: 'As more searches are answered directly by ChatGPT, Perplexity, and Google\'s AI Overviews, visibility in traditional search results is no longer the whole picture. We optimise your content structure, authority signals, and E-E-A-T positioning so AI engines cite your brand as the definitive source in your niche — before your competitors figure this out.',
      image: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1555255707-c07966088b7b?w=800&h=500&fit=crop',
      ],
      badge: 'Hot',
      deliveryDays: 30,
      startingPrice: 349,
      subOptionKey: 'AI Engine Optimization',
      features: ['FAQ & structured data strategy', 'Authority content clusters', 'LLM citation building'],
    },
    {
      id: 'keyword-research',
      name: 'Keyword Research & Strategy',
      description: 'Deep keyword analysis to find your highest-value opportunities — the terms your competitors haven\'t cornered yet.',
      detailDescription: 'Ranking for the wrong keywords is worse than not ranking at all — you get traffic that doesn\'t buy. We build a 100+ keyword opportunity map using Ahrefs and SEMrush data, segmented by search intent, competition level, and revenue potential. Your SEO investment goes exactly where it generates returns.',
      image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1543286386-713bdd548da4?w=800&h=500&fit=crop',
      ],
      deliveryDays: 5,
      startingPrice: 99,
      subOptionKey: 'Keyword Research',
      features: ['100+ keyword opportunity report', 'Search intent mapping', 'Competitor keyword gap analysis'],
    },
    {
      id: 'link-building',
      name: 'Link Building',
      description: 'High-authority backlinks from real websites in your niche — the fuel that pushes you to page one.',
      detailDescription: 'Backlinks remain the single strongest ranking signal Google uses, and quality matters far more than quantity. We secure editorial placements on real, relevant websites with DR40+ authority through digital PR, guest posting, and niche outreach. Every link we build is one your competitors can\'t easily replicate.',
      image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1553484771-371a605b060b?w=800&h=500&fit=crop',
      ],
      deliveryDays: 30,
      startingPrice: 249,
      subOptionKey: 'Link Building',
      features: ['DR40+ backlinks from niche sites', 'Guest posting & digital PR', 'Anchor text strategy'],
    },
  ],
  faqs: [
    { q: 'How long does SEO take to show results?', a: 'You will typically see movement in rankings within 60–90 days. Significant traffic growth usually shows at 3–6 months. SEO compounds over time — the longer you invest, the stronger the returns.' },
    { q: 'What is AEO and why does it matter?', a: 'AEO (Answer Engine Optimisation) ensures your brand appears in AI-generated answers from tools like ChatGPT, Perplexity, and Google\'s AI Overviews. As AI search grows, AEO is the new frontier of organic visibility.' },
    { q: 'Do you write the content as well?', a: 'Yes. Standard and Authority packages include SEO content written by human experts (not AI spam) and optimised to rank and convert.' },
    { q: 'Can you guarantee page 1 rankings?', a: 'No ethical SEO agency can guarantee specific rankings — Google\'s algorithm is outside anyone\'s control. What we guarantee is consistent, measurable progress backed by data every month.' },
    { q: 'What tools do you use for reporting?', a: 'We use Google Search Console, Ahrefs, SEMrush, and a custom client dashboard showing keyword positions, organic traffic, and backlink growth in real time.' },
  ],
  reviewCount: 221,
  totalOrders: '420+',
};

export const SEOAEOPage: React.FC = () => <ServiceGigPage {...data} serviceSlug="seo-aeo" />;
