import React from 'react';
import { ShoppingCart } from 'lucide-react';
import { ServiceGigPage, ServiceGigPageProps } from '@/components/templates/ServiceGigPage';

const data: ServiceGigPageProps = {
  serviceName: 'Shop Management',
  tagline: 'I will set up, optimise, and fully manage your online store so it sells while you sleep',
  icon: <ShoppingCart className="w-6 h-6 text-red-500" />,
  tags: ['Amazon Store', 'TikTok Shop', 'eBay Store', 'Daraz Store', 'Product Listing', 'Inventory Management'],
  heroImage: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&h=675&fit=crop',
  galleryImages: [
    'https://images.unsplash.com/photo-1553895501-af9e282e7fc1?w=1200&h=675&fit=crop',
    'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=1200&h=675&fit=crop',
    'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&h=675&fit=crop',
  ],
  about:
    'Running an e-commerce store is a full-time job — and most sellers are leaving money on the table through poor listings, slow fulfilment, and missed optimisations. We provide end-to-end shop management across Amazon, TikTok Shop, eBay, and Daraz: product listing creation, SEO-optimised titles and descriptions, A+ content, inventory forecasting, order management, and performance analytics. Our managed stores average 40% revenue growth within 90 days.',
  packages: [
    {
      name: 'Basic',
      label: 'Starter',
      price: 149,
      originalPrice: 199,
      delivery: 'Monthly',
      revisions: '2',
      description: 'Single-platform management for sellers just getting started.',
      features: [
        '1 platform (Amazon OR TikTok OR eBay)',
        'Up to 20 product listings',
        'SEO-optimised titles & descriptions',
        'Keyword research & backend search terms',
        'Monthly performance report',
      ],
    },
    {
      name: 'Standard',
      label: 'Growth',
      price: 299,
      originalPrice: 399,
      delivery: 'Monthly',
      revisions: '5',
      description: 'Two-platform management with product photography briefing and ads.',
      features: [
        '2 platforms',
        'Up to 50 product listings',
        'A+ Content / Enhanced Brand Content',
        'PPC / Sponsored Products setup',
        'Inventory forecasting & alerts',
        'Competitor pricing analysis',
        'Bi-weekly strategy call',
      ],
    },
    {
      name: 'Premium',
      label: 'Full Management',
      price: 499,
      originalPrice: 699,
      delivery: 'Monthly',
      revisions: 'Unlimited',
      description: 'Complete hands-off management across all your platforms — fully done for you.',
      features: [
        'All platforms — unlimited listings',
        'Full PPC management',
        'Order & return management',
        'Supplier & inventory coordination',
        'Product launch strategy',
        'Review management',
        'Dedicated account manager',
        'Weekly performance dashboard',
      ],
    },
  ],
  subServices: [
    {
      id: 'amazon',
      name: 'Amazon Store Management',
      description: 'Full Amazon account management — listings, A+ content, sponsored ads, and inventory — to maximise your Buy Box and BSR.',
      detailDescription: 'Amazon is a search engine for buyers with wallets open — and winning here means owning the Buy Box. We manage your entire seller account, from listing creation and A+ content to Sponsored Products campaigns and inventory health. One goal: maximise your Best Seller Rank and protect your account standing.',
      image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=800&h=500&fit=crop',
      ],
      badge: 'Most Popular',
      deliveryDays: 30,
      startingPrice: 149,
      subOptionKey: 'Amazon Store',
      features: ['Listing creation & SEO', 'A+ Content & Brand Store', 'Sponsored Products management'],
    },
    {
      id: 'tiktok-shop',
      name: 'TikTok Shop Management',
      description: 'Set up and manage your TikTok Shop — product listings, affiliate outreach, live shopping, and ad campaigns.',
      detailDescription: 'TikTok Shop is the fastest-growing social commerce platform right now, and the window to stake your position is open today. We set up your shop, optimise every listing for the algorithm, recruit affiliate creators, and manage live shopping events that generate real-time sales spikes. First-mover advantage is real here.',
      image: 'https://images.unsplash.com/photo-1611162617263-4ec3d744e0a3?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1611162617263-4ec3d744e0a3?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=800&h=500&fit=crop',
      ],
      badge: 'Hot',
      deliveryDays: 30,
      startingPrice: 149,
      subOptionKey: 'TikTok Shop',
      features: ['Shop setup & product listings', 'Affiliate creator outreach', 'LIVE shopping event management'],
    },
    {
      id: 'ebay',
      name: 'eBay Store Management',
      description: 'eBay listing optimisation, Cassini search ranking, promoted listings, and feedback management to grow your store.',
      detailDescription: 'eBay\'s Cassini algorithm rewards sellers who optimise — and quietly buries those who don\'t. We optimise your titles, item specifics, categories, and promoted listings to rank at the top of eBay search, while maintaining the seller metrics that keep your account in Top Rated status.',
      image: 'https://images.unsplash.com/photo-1553895501-af9e282e7fc1?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1553895501-af9e282e7fc1?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&h=500&fit=crop',
      ],
      deliveryDays: 30,
      startingPrice: 129,
      subOptionKey: 'eBay Store',
      features: ['Cassini-optimised listings', 'Promoted Listings management', 'Feedback & return handling'],
    },
    {
      id: 'daraz',
      name: 'Daraz Store Management',
      description: 'Full Daraz seller account management — listings, Daraz Ads, flash sale participation, and customer service.',
      detailDescription: 'Daraz dominates South Asian e-commerce and we know the platform\'s ranking system inside out. We handle listing optimisation, Daraz Ads setup and management, flash sale participation, and customer service — all designed to grow your seller score and increase your monthly GMV consistently.',
      image: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1553895501-af9e282e7fc1?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=800&h=500&fit=crop',
      ],
      badge: 'Bestseller',
      deliveryDays: 30,
      startingPrice: 99,
      subOptionKey: 'Daraz Store',
      features: ['Listing optimisation', 'Daraz Ads management', 'Flash sale & campaign participation'],
    },
    {
      id: 'product-listing',
      name: 'Product Listing Creation',
      description: 'Conversion-optimised product titles, bullet points, descriptions, and keyword-rich backend terms — for any platform.',
      detailDescription: 'Your product listing is your sales page — and a weak title, thin description, or missing keywords means you\'re invisible to buyers already searching. We write SEO-optimised, conversion-focused listings that rank on the platform and compel browsers to buy. Available for Amazon, TikTok Shop, eBay, Daraz, and Shopify.',
      image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=500&fit=crop',
      ],
      deliveryDays: 3,
      startingPrice: 49,
      subOptionKey: 'Product Listing',
      features: ['SEO keyword research', 'Compelling copy & formatting', 'Platform-specific best practices'],
    },
    {
      id: 'inventory-management',
      name: 'Inventory Management',
      description: 'Demand forecasting, reorder alerts, and supplier coordination to ensure you never run out of stock — or overstock.',
      detailDescription: 'Running out of stock costs you ranking, sales, and customer trust — all at the same time. We build a demand forecasting model using your historical sales data and seasonal trends, set intelligent reorder alerts, and coordinate with your suppliers directly so you\'re always in stock without tying up cash in excess inventory.',
      image: 'https://images.unsplash.com/photo-1553895501-af9e282e7fc1?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1553895501-af9e282e7fc1?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=500&fit=crop',
      ],
      deliveryDays: 7,
      startingPrice: 99,
      subOptionKey: 'Inventory Management',
      features: ['Demand forecasting model', 'Low-stock alerts & reorder points', 'Supplier communication management'],
    },
  ],
  faqs: [
    { q: 'Do I need to give you access to my seller account?', a: 'Yes — we will need sub-user or delegated access to manage your account. We use read/write permissions only and never have access to your financial payout settings.' },
    { q: 'How quickly will I see revenue growth?', a: 'Most clients see ranking and conversion improvements within 30 days for listing optimisation. PPC and full account management typically shows ROI improvement by month 2.' },
    { q: 'Do you manage ads as well as listings?', a: 'Yes. Standard and Premium packages include PPC / Sponsored Products management on every supported platform.' },
    { q: 'Can you help with product sourcing?', a: 'We do not source directly, but our Premium package includes supplier coordination and we can refer you to vetted sourcing agents for your niche.' },
    { q: 'What if I sell on multiple platforms?', a: 'Our Standard package covers 2 platforms and Premium covers all platforms. We centralise reporting so you get a single view of performance across all channels.' },
  ],
  reviewCount: 154,
  totalOrders: '280+',
};

export const ShopManagementPage: React.FC = () => <ServiceGigPage {...data} serviceSlug="shop-management" />;
