import React from 'react';
import { Film } from 'lucide-react';
import { ServiceGigPage, ServiceGigPageProps } from '@/components/templates/ServiceGigPage';

const data: ServiceGigPageProps = {
  serviceName: 'Video Editing',
  tagline: 'I will transform your raw footage into cinematic, scroll-stopping videos that drive real engagement',
  icon: <Film className="w-6 h-6 text-red-500" />,
  tags: ['YouTube Videos', 'Reels / TikTok', 'Product Videos', 'Motion Graphics', 'Color Grading', 'Subtitles & Captions'],
  heroImage: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=1200&h=675&fit=crop',
  galleryImages: [
    'https://images.unsplash.com/photo-1492619375914-88005aa9e8fb?w=1200&h=675&fit=crop',
    'https://images.unsplash.com/photo-1536240478700-b869ad10e128?w=1200&h=675&fit=crop',
    'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=1200&h=675&fit=crop',
  ],
  about:
    'Video is the most powerful content format alive — and most brands are leaving 90% of its potential on the table with poor editing. We edit YouTube long-forms, viral Reels, TikTok content, product demos, and brand films. Every project gets professional colour grading, sound design, motion graphics, and platform-optimised formatting. Our editors have cut content for brands with 50M+ combined subscribers.',
  packages: [
    {
      name: 'Basic',
      label: 'Single Video',
      price: 99,
      originalPrice: 149,
      delivery: '3 Days',
      revisions: '2',
      description: 'One polished video — trimmed, colour-graded, and export-ready for your platform.',
      features: [
        '1 video up to 10 minutes',
        'Cuts, transitions & pacing',
        'Colour correction & grading',
        'Background music (licensed)',
        'Subtitles / captions',
        'Platform-optimised export',
      ],
    },
    {
      name: 'Standard',
      label: '5 Video Pack',
      price: 249,
      originalPrice: 349,
      delivery: '7 Days',
      revisions: '5',
      description: '5 videos edited to a consistent style — ideal for creators posting weekly.',
      features: [
        '5 videos up to 10 min each',
        'Consistent colour grade / style guide',
        'Motion graphic intro / outro',
        'Sound design & mixing',
        'Subtitles in up to 2 languages',
        'Short-form repurpose cuts (Reels/TikTok)',
      ],
    },
    {
      name: 'Premium',
      label: 'Full Package',
      price: 549,
      originalPrice: 799,
      delivery: '14 Days',
      revisions: 'Unlimited',
      description: '10 videos with advanced motion graphics, cinematic grade, and full post-production.',
      features: [
        '10 videos — any length or format',
        'Custom motion graphics & animations',
        'Cinematic colour grading (LUT)',
        'Professional sound design',
        'AI-generated subtitles (5 languages)',
        'Thumbnail design (each video)',
        'Short-form repurpose pack',
      ],
    },
  ],
  subServices: [
    {
      id: 'youtube',
      name: 'YouTube Video Editing',
      description: 'Long-form YouTube content edited to maximise watch time, click-through rate, and channel growth.',
      detailDescription: 'YouTube is a search engine, not just a video platform — and we edit with that in mind. We structure your videos for maximum watch time, pace them for retention, and layer in B-roll and motion graphics that keep viewers engaged to the end. More watch time means more algorithm distribution and faster channel growth.',
      image: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1492619375914-88005aa9e8fb?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&h=500&fit=crop',
      ],
      badge: 'Most Popular',
      deliveryDays: 3,
      startingPrice: 99,
      subOptionKey: 'YouTube Videos',
      features: ['Retention-optimised pacing', 'B-roll & motion graphics', 'Thumbnail design included'],
    },
    {
      id: 'reels-tiktok',
      name: 'Reels & TikTok Editing',
      description: 'Hook-first short-form videos engineered for the algorithm — fast cuts, captions, and trending audio.',
      detailDescription: 'Short-form content lives or dies in the first 1.5 seconds. We build every Reel and TikTok with a scroll-stopping hook, kinetic pacing, trending audio, and animated captions that drive shares and saves. Platform-native edits built for the algorithm — not just repurposed YouTube clips squeezed into a vertical frame.',
      image: 'https://images.unsplash.com/photo-1611162617263-4ec3d744e0a3?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1611162617263-4ec3d744e0a3?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=800&h=500&fit=crop',
      ],
      badge: 'Hot',
      deliveryDays: 2,
      startingPrice: 49,
      subOptionKey: 'Reels / TikTok',
      features: ['Hook-first structure', 'Trending audio sync', 'Auto captions & text animations'],
    },
    {
      id: 'product-videos',
      name: 'Product Videos',
      description: 'Cinematic product showcase videos that highlight features, build desire, and drive purchase decisions.',
      detailDescription: 'Your product video is often the last piece of content a buyer sees before they purchase — make it count. We edit cinematic showcase videos that highlight your product\'s best features, build genuine desire, and eliminate buyer hesitation. Formatted for ads, product pages, and social media in every required aspect ratio.',
      image: 'https://images.unsplash.com/photo-1492619375914-88005aa9e8fb?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1492619375914-88005aa9e8fb?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&h=500&fit=crop',
      ],
      badge: 'Bestseller',
      deliveryDays: 5,
      startingPrice: 149,
      subOptionKey: 'Product Videos',
      features: ['Product hero shots', 'Feature callout animations', 'E-commerce platform formats'],
    },
    {
      id: 'motion-graphics',
      name: 'Motion Graphics & Animation',
      description: 'Custom animated intros, outros, lower thirds, and explainer animations that elevate your brand.',
      detailDescription: 'Motion graphics are what separate amateur video content from premium branded productions. We create custom logo animations, lower thirds, transitions, and explainer sequences in After Effects that make your brand look as serious as it is — and as polished as your biggest competitor.',
      image: 'https://images.unsplash.com/photo-1536240478700-b869ad10e128?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1536240478700-b869ad10e128?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800&h=500&fit=crop',
      ],
      deliveryDays: 7,
      startingPrice: 199,
      subOptionKey: 'Motion Graphics',
      features: ['Custom logo animation', 'Animated lower thirds', 'Explainer / infographic animation'],
    },
    {
      id: 'color-grading',
      name: 'Colour Grading',
      description: 'Professional colour grading with custom LUTs that give your footage a cinematic, consistent look.',
      detailDescription: 'Colour is the difference between amateur footage and a cinematic film. We develop a custom LUT matched to your brand\'s visual identity and grade every scene consistently — so your content looks intentional, premium, and instantly recognisable across every platform\'s display specification.',
      image: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1492619375914-88005aa9e8fb?w=800&h=500&fit=crop',
      ],
      deliveryDays: 2,
      startingPrice: 79,
      subOptionKey: 'Color Grading',
      features: ['Custom LUT creation', 'Scene-by-scene colour match', 'HDR & platform-safe export'],
    },
    {
      id: 'subtitles',
      name: 'Subtitles & Captions',
      description: 'Accurate, styled subtitles and captions that boost accessibility, watch time, and international reach.',
      detailDescription: '85% of social video is watched without sound. Accurate, styled captions aren\'t optional — they\'re essential for watch time, accessibility, and international reach. We transcribe, manually clean, and animate your subtitles so they enhance the viewing experience rather than distract from it.',
      image: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1536240478700-b869ad10e128?w=800&h=500&fit=crop',
      ],
      deliveryDays: 1,
      startingPrice: 29,
      subOptionKey: 'Subtitles & Captions',
      features: ['AI-transcribed + human-proofed', 'Animated caption styles', 'Up to 5 language translations'],
    },
  ],
  faqs: [
    { q: 'What footage formats do you accept?', a: 'We accept all major formats: MP4, MOV, AVI, MKV, RAW footage from any camera. Just upload to Google Drive / Dropbox and share the link.' },
    { q: 'Can you match a specific editing style?', a: 'Yes. Send us 2–3 reference videos and we will replicate the pacing, colour grade, and style for your content.' },
    { q: 'Do you provide the project files?', a: 'Source files (Premiere Pro / DaVinci Resolve) are included in Standard and Premium packages, or available as an add-on for Basic.' },
    { q: 'How do I send raw footage?', a: 'Upload to Google Drive, Dropbox, WeTransfer, or Frame.io and share the link in your order brief. We handle files up to 200GB.' },
    { q: 'Do you do music licensing?', a: 'Yes. We use Epidemic Sound and Artlist libraries (royalty-free). If you need sync-licensed tracks for ads or branded content, we can source those too.' },
  ],
  reviewCount: 189,
  totalOrders: '350+',
};

export const VideoEditingPage: React.FC = () => <ServiceGigPage {...data} serviceSlug="video-editing" />;
