import React from 'react';
import { Code2 } from 'lucide-react';
import { ServiceGigPage, ServiceGigPageProps } from '@/components/templates/ServiceGigPage';

const data: ServiceGigPageProps = {
  serviceName: 'Web Development',
  tagline: 'I will build you a blazing-fast, conversion-first website that dominates your market',
  icon: <Code2 className="w-6 h-6 text-red-500" />,
  tags: ['WordPress', 'Shopify', 'React', 'Node.js'],
  heroImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&h=675&fit=crop',
  galleryImages: [
    'https://images.unsplash.com/photo-1547658719-da2b51169166?w=1200&h=675&fit=crop',
    'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=1200&h=675&fit=crop',
    'https://images.unsplash.com/photo-1593720213428-28a5b9e94613?w=1200&h=675&fit=crop',
  ],
  about:
    'We craft high-performance web experiences engineered for one outcome — growth. From lightning-fast WordPress sites and fully customised Shopify stores to scalable React SPAs and robust Node.js backends, every line of code is written with conversion optimisation, Core Web Vitals, and long-term maintainability in mind. We have delivered 200+ projects across e-commerce, SaaS, and lead-generation verticals — each one outperforming its predecessor.',
  packages: [
    {
      name: 'Basic',
      label: 'Starter',
      price: 349,
      originalPrice: 499,
      delivery: '7 Days',
      revisions: '2',
      description: 'Perfect for small businesses needing a clean, professional 3-page website fast.',
      features: [
        'Up to 3 pages (Home, About, Contact)',
        'Mobile-responsive design',
        'WordPress or Shopify setup',
        'Basic SEO configuration',
        'Contact form integration',
        '1-month post-launch support',
      ],
    },
    {
      name: 'Standard',
      label: 'Growth',
      price: 699,
      originalPrice: 999,
      delivery: '14 Days',
      revisions: '5',
      description: 'Full business website with up to 7 pages, custom design, and integrations.',
      features: [
        'Up to 7 pages with custom design',
        'WooCommerce / Shopify storefront',
        'Payment gateway integration',
        'Advanced SEO + sitemap setup',
        'Google Analytics & Tag Manager',
        'Performance optimisation (95+ score)',
        '3-month post-launch support',
      ],
    },
    {
      name: 'Premium',
      label: 'Enterprise',
      price: 1749,
      originalPrice: 2499,
      delivery: '21 Days',
      revisions: 'Unlimited',
      description: 'Fully custom full-stack web application with backend, API, and scalable architecture.',
      features: [
        'Unlimited pages — custom design system',
        'React / Next.js SPA or SSR',
        'Node.js / Express REST API',
        'MongoDB / PostgreSQL database',
        'Authentication & user roles',
        'Admin dashboard',
        'CI/CD deployment pipeline',
        '6-month post-launch support',
      ],
    },
  ],
  subServices: [
    {
      id: 'wordpress',
      name: 'WordPress Development',
      description: 'Custom WordPress sites built for speed, SEO, and conversions — from landing pages to full e-commerce.',
      detailDescription: 'We build custom WordPress websites engineered for speed, search visibility, and conversions. Whether it\'s a brochure site, landing page, or full WooCommerce store, every theme is hand-coded — no bloated page builders. You get a site that scores 90+ on Core Web Vitals, ranks on Google, and turns your traffic into revenue.',
      image: 'https://images.unsplash.com/photo-1559028012-481c04fa702d?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1559028012-481c04fa702d?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=800&h=500&fit=crop',
      ],
      badge: 'Bestseller',
      deliveryDays: 7,
      startingPrice: 299,
      subOptionKey: 'WordPress',
      features: ['Custom theme development', 'WooCommerce integration', 'Plugin setup & configuration'],
    },
    {
      id: 'shopify',
      name: 'Shopify Store Development',
      description: 'High-converting Shopify stores with custom themes, app integrations, and checkout optimisation.',
      detailDescription: 'Your Shopify store should do the selling for you. We craft custom storefronts with conversion-focused layouts, streamlined checkout flows, and the right app integrations to maximise average order value. Whether you\'re launching from scratch or migrating from another platform, we build stores built to scale.',
      image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=800&h=500&fit=crop',
      ],
      badge: 'Most Popular',
      deliveryDays: 10,
      startingPrice: 399,
      subOptionKey: 'Shopify',
      features: ['Custom Shopify theme', 'Payment & shipping setup', 'Multi-currency support'],
    },
    {
      id: 'react',
      name: 'React / Next.js Development',
      description: 'Blazing-fast single-page apps and server-rendered websites with React and Next.js.',
      detailDescription: 'When templates won\'t cut it, we build high-performance React and Next.js applications from scratch. Server-side rendering, edge caching, and an API-first architecture deliver blazing speeds globally. Ideal for SaaS platforms, client portals, and content-heavy sites that need to grow without limits.',
      image: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1593720213428-28a5b9e94613?w=800&h=500&fit=crop',
      ],
      badge: 'Hot',
      deliveryDays: 14,
      startingPrice: 599,
      subOptionKey: 'React',
      features: ['Next.js SSR / SSG', 'Tailwind CSS design system', 'REST / GraphQL API integration'],
    },
    {
      id: 'nodejs',
      name: 'Node.js Backend Development',
      description: 'Scalable REST APIs and backend services built with Node.js, Express, and MongoDB / PostgreSQL.',
      detailDescription: 'Your frontend is only as powerful as the backend behind it. We design and build scalable REST APIs, authentication systems, and database architectures using Node.js, Express, and MongoDB or PostgreSQL. Clean code, full documentation, and built to handle your traffic from day one.',
      image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&h=500&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=500&fit=crop',
        'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&h=500&fit=crop',
      ],
      deliveryDays: 14,
      startingPrice: 499,
      subOptionKey: 'Node.js',
      features: ['Express REST API', 'Database design', 'JWT auth & role management'],
    },
  ],
  faqs: [
    { q: 'What information do you need to get started?', a: 'We need your brand assets (logo, colors, fonts if any), a list of pages/features you want, and any reference websites you like. We handle the rest.' },
    { q: 'Do you provide hosting?', a: 'We do not host directly, but we set up everything on your preferred host (Vercel, WP Engine, Shopify, AWS, etc.) and guide you through the process.' },
    { q: 'How many revision rounds are included?', a: 'Depending on your package: Basic (2), Standard (5), Premium (Unlimited). Revisions cover design changes and functionality tweaks within the original scope.' },
    { q: 'Can I upgrade my package mid-project?', a: 'Yes, you can upgrade at any time. We will adjust the timeline and invoice for the difference only.' },
    { q: 'Do you maintain websites after launch?', a: 'Yes. Maintenance retainers are available monthly. We also include post-launch support in every package (duration varies by tier).' },
  ],
  reviewCount: 312,
  totalOrders: '600+',
};

export const WebDevelopmentPage: React.FC = () => <ServiceGigPage {...data} serviceSlug="web-development" />;
